/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
const express = require("express");
const bodyParser = require("body-parser");
const fs = require("fs");

const app = express();

app.use(bodyParser.json());

app.get("/todos", (req, res) => {
  fs.readFile("todos.json", "utf-8", (err, data) => {
    res.json(data);
  });
});

app.get("/todos/:id", (req, res) => {
  const id = parseInt(req.params.id);
  fs.readFile("todos.json", "utf-8", (err, data) => {
    const filter = data.filter((todo) => todo.id == id);
    if (filter.length == 0) res.status(404).send("Not found");
    else res.json(filter[0].todoContent);
  });
});

app.post("/todos", (req, res) => {
  const todo = req.body;
  fs.readFile("todos.json", "utf-8", (err, data) => {
    const json = JSON.parse(data);
    const uid = Math.floor(Math.random() * 1000000);
    json.push({ id: uid, todoContent: todo });
    const updatedData = JSON.stringify(json);
    fs.writeFile("todos.json", updatedData, (err) => {
      res.status(201).json({ id: uid });
    });
  });
});

app.put("/todos/:id", (req, res) => {
  const id = parseInt(req.params.id);
  const todo = req.body;
  fs.readFile("todos.json", "utf-8", (err, data) => {
    const json = JSON.parse(data);
    let todoIndex = -1;
    for (let i = 0; i < json.length; i++) {
      if (json[i].id == id) todoIndex = i;
    }
    if (todoIndex == -1) res.status(404).send("Not found");
    else {
      json[todoIndex].todoContent = todo;
      const updatedData = JSON.stringify(json);
      fs.writeFile("todos.json", updatedData, (err) => {
        res.send("");
      });
    }
  });
});

app.delete("/todos/:id", (req, res) => {
  const id = parseInt(req.params.id);
  fs.readFile("todos.json", "utf-8", (err, data) => {
    let json = JSON.parse(data);
    const filter = json.filter((todo) => todo.id != id);
    console.log(filter);
    console.log(json);
    if (filter.length == json.length) res.status(404).send("Not found");
    else {
      json = filter;
      const updatedData = JSON.stringify(json);
      fs.writeFile("todos.json", updatedData, (err) => {
        res.send("");
      });
    }
  });
});

app.all("*", (req, res) => {
  res.status(404).send("Route not found");
});

app.listen(3000);

module.exports = app;
